version: "3.3"
services:
  clamd:
    image: mailu/clamav:1.8
    restart: unless-stopped
    ports:
      - 127.0.0.1:3310:3310
  clamd-api:
    image: benzino77/clamav-rest-api
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - clamd
    environment:
      - NODE_ENV=production
      - CLAMD_IP=clamd
      - APP_FORM_KEY=FILES
      - APP_PORT=3000
    ports:
      - 127.0.0.1:3000:3000

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    expose:
      - 27017
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGODB_DATABASE=alex
      - ALLOW_EMPTY_PASSWORD=yes
